name: Build LoraOS ISO

on: [push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Sau v5 dacă a ieșit deja
      
      - name: Install Compilers
        run: |
          sudo apt update
          sudo apt install -y gcc-i686-linux-gnu nasm xorriso grub-pc-bin mtools

      - name: Compile Kernel
        run: make

      - name: Create ISO
        run: make iso

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LoraOS-ISO
          path: loraos.iso
